# Generated by Django 2.1.7 on 2020-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_free_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='category2',
            field=models.CharField(choices=[('음악방송', '음악방송'), ('기타', '기타')], default='기타', max_length=18, verbose_name='카테고리'),
        ),
    ]
