# Generated by Django 2.1.7 on 2020-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_auto_20200808_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='category2',
            field=models.CharField(choices=[('음악방송', '음악방송'), ('뮤직비디오', '뮤직비디오'), ('공연', '공연'), ('기타', '기타')], default='기타', max_length=18, verbose_name='카테고리'),
        ),
    ]
