# Generated by Django 2.1.7 on 2020-08-09 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0004_auto_20200809_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
