# Generated by Django 2.1.7 on 2020-08-13 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0006_remove_free_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
