# Generated by Django 2.1.7 on 2020-08-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_free_like_user_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='like_user_set',
        ),
    ]
