# Generated by Django 2.1.7 on 2020-08-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0010_auto_20200814_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='like_user_set',
        ),
        migrations.AddField(
            model_name='free',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='free.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='free',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='free.Free'),
        ),
    ]
